package uas.mvc.views;

import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uas.mvc.controllers.AnggotaController;
import uas.mvc.controllers.AngsuranController;
import uas.mvc.controllers.PinjamanController;
import uas.mvc.models.Anggota;
import uas.mvc.models.Angsuran;
import uas.mvc.models.CRUD;
import uas.mvc.models.Pinjaman;
import uas.mvc.models.SaldoAnggota;
import uas.mvc.utils.Helpers;

/**
 *
 * @author agus
 */
public class AngsuranPage extends javax.swing.JPanel {

    private DefaultTableModel tblModel;
    private final AnggotaController anggotaController = new AnggotaController();
    private final PinjamanController pinjamanController = new PinjamanController();
    private final AngsuranController angsuranController = new AngsuranController();

    public AngsuranPage() {
        initComponents();

        setDataAnggota(anggotaController.fetchAnggota());
        setDataAngsuran(angsuranController.fetchAngsuran());
        setDataPinjaman();
    }

    private void setDataAnggota(List<Anggota> dataAnggota) {
        if (dataAnggota == null) {
            JOptionPane.showMessageDialog(this, "Data Anggota tidak bisa di load", "Gagal Koneksi",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            inputAnggota.setModel(new DefaultComboBoxModel(dataAnggota.toArray()));
        }
    }

    private void setDataAngsuran(List<Angsuran> dataAngsuran) {
        if (dataAngsuran == null) {
            JOptionPane.showMessageDialog(this, "Data Angsuran tidak bisa di load", "Gagal Koneksi",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            tblModel = new DefaultTableModel();
            tblModel.setColumnIdentifiers(new String[]{"ID", "ID Pinjaman", "Total Pinjaman", "NIK", "Nama Anggota", "Jumlah", "Keterangan", "Tanggal Transaksi"});

            DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

            for (Angsuran angsuran : dataAngsuran) {
                Object[] o = new Object[9];
                o[0] = angsuran.getId();
                o[1] = angsuran.getPinjaman().getId();
                o[2] = Helpers.formatRupiah(angsuran.getPinjaman().getTotalPinjaman());
                o[3] = angsuran.getAnggota().getNik();
                o[4] = angsuran.getAnggota().getNama();
                o[5] = Helpers.formatRupiah(angsuran.getJumlah());
                o[6] = angsuran.getKeterangan();
                o[7] = df.format(angsuran.getTanggalTransaksi());
                tblModel.addRow(o);
            }

            tblPinjaman.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            tblPinjaman.setModel(tblModel);
        }
    }

    private void resetForm() {
        inputIdAngsuran.setText("");
        inputIdAngsuran.setEnabled(false);
        inputJumlah.setText("");
        inputKeterangan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupType = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputAnggota = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        inputJumlah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputKeterangan = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        inputIdAngsuran = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputPinjaman = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputIdPinjaman = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        inputSisaPinjaman = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPinjaman = new javax.swing.JTable();

        jLabel3.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Data Angsuran");

        jLabel1.setText("Anggota:");

        inputAnggota.setForeground(new java.awt.Color(0, 0, 0));
        inputAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAnggotaActionPerformed(evt);
            }
        });

        jLabel2.setText("Jumlah:");

        inputJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputJumlahKeyTyped(evt);
            }
        });

        jLabel5.setText("Keterangan:");

        inputKeterangan.setColumns(20);
        inputKeterangan.setRows(5);
        jScrollPane1.setViewportView(inputKeterangan);

        jLabel6.setText("ID Angsuran:");

        inputIdAngsuran.setEnabled(false);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Fira Sans", 2, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("*Kode Transaksi akan di generate otomatis");

        jLabel9.setText("Total Pinjaman:");

        inputPinjaman.setEnabled(false);

        jLabel4.setText("ID Pinjaman:");

        inputIdPinjaman.setEnabled(false);

        jLabel10.setText("Sisa Pinjaman:");

        inputSisaPinjaman.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(btnSimpan)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addComponent(inputAnggota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputJumlah)
                    .addComponent(inputIdAngsuran)
                    .addComponent(inputPinjaman)
                    .addComponent(inputIdPinjaman)
                    .addComponent(inputSisaPinjaman))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputIdAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputIdPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(inputPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inputSisaPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tblPinjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Pinjaman", "Total Pinjaman", "NIK", "Nama Anggota", "Jumlah", "Keterangan", "Tanggal Transaksi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPinjaman);
        if (tblPinjaman.getColumnModel().getColumnCount() > 0) {
            tblPinjaman.getColumnModel().getColumn(7).setResizable(false);
            tblPinjaman.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3)
                    .addContainerGap(806, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputJumlahKeyTyped
        Helpers.inputNumeric(evt);
    }//GEN-LAST:event_inputJumlahKeyTyped

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (validateInput()) {
            Angsuran angsuran = new Angsuran()
                    .setJumlah(Long.parseLong(inputJumlah.getText()))
                    .setKeterangan(inputKeterangan.getText())
                    .setAnggota((Anggota) inputAnggota.getSelectedItem())
                    .setPinjaman(new Pinjaman(Integer.parseInt(inputIdPinjaman.getText())));

            angsuranController.setDML(angsuran, CRUD.CREATE);
            JOptionPane.showMessageDialog(this, "Berhasil membayar angsuran pinjaman.");

            resetForm();
            setDataAngsuran(angsuranController.fetchAngsuran());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void inputAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAnggotaActionPerformed
        setDataPinjaman();
    }//GEN-LAST:event_inputAnggotaActionPerformed

    private void setDataPinjaman() {
        Anggota anggotaSelected = (Anggota) inputAnggota.getSelectedItem();
        Anggota anggota = anggotaController.getAnggotaByNIK(anggotaSelected.getNik());

        Pinjaman pinjamanBelumLunas = pinjamanController.getPinjamanBelumLuasByAnggota(anggota);

        if (pinjamanBelumLunas != null) {
            inputIdPinjaman.setText(pinjamanBelumLunas.getId() + "");
            inputPinjaman.setText(Helpers.formatRupiah(pinjamanBelumLunas.getTotalPinjaman()));
            inputSisaPinjaman.setText(Helpers.formatRupiah(
                    anggota.getSaldoAnggota().getSisaPinjaman()
            ));
        } else {
            inputIdPinjaman.setText("");
            inputPinjaman.setText("");
            inputSisaPinjaman.setText("");
        }

    }

    private boolean validateInput() {
        if (inputJumlah.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Jumlah Tidak Boleh Kosong");
            return false;
        } else if (inputIdPinjaman.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tidak ada pinjaman di anggota ini.");
        } else {
            return true;
        }

        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupType;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> inputAnggota;
    private javax.swing.JTextField inputIdAngsuran;
    private javax.swing.JTextField inputIdPinjaman;
    private javax.swing.JTextField inputJumlah;
    private javax.swing.JTextArea inputKeterangan;
    private javax.swing.JTextField inputPinjaman;
    private javax.swing.JTextField inputSisaPinjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPinjaman;
    // End of variables declaration//GEN-END:variables
}
