package uas.mvc.views;

import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uas.mvc.controllers.AnggotaController;
import uas.mvc.controllers.PinjamanController;
import uas.mvc.models.Anggota;
import uas.mvc.models.CRUD;
import uas.mvc.models.Pinjaman;
import uas.mvc.utils.Helpers;

/**
 *
 * @author agus
 */
public class PinjamanPage extends javax.swing.JPanel {

    private DefaultTableModel tblModel;
    private final AnggotaController anggotaController = new AnggotaController();
    private final PinjamanController pinjamanController = new PinjamanController();

    public PinjamanPage() {
        initComponents();

        setDataAnggota(anggotaController.fetchAnggota());
        setDataPinjaman(pinjamanController.fetchPinjaman());
    }

    private void setDataAnggota(List<Anggota> dataAnggota) {
        if (dataAnggota == null) {
            JOptionPane.showMessageDialog(this, "Data pinjaman tidak bisa di load", "Gagal Koneksi",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            inputAnggota.setModel(new DefaultComboBoxModel(dataAnggota.toArray()));
        }
    }

    private void setDataPinjaman(List<Pinjaman> dataPinjaman) {
        if (dataPinjaman == null) {
            JOptionPane.showMessageDialog(this, "Data Pinjaman tidak bisa di load", "Gagal Koneksi",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            tblModel = new DefaultTableModel();
            tblModel.setColumnIdentifiers(new String[]{"ID", "NIK", "Nama Anggota", "Jumlah", "Tipe Transaksi", "Saldo Awal", "Saldo Akhir", "Keterangan", "Tanggal Transaksi"});

            DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

            for (Pinjaman pinjaman : dataPinjaman) {
                Object[] o = new Object[9];
                o[0] = pinjaman.getId();
                o[1] = pinjaman.getAnggota().getNik();
                o[2] = pinjaman.getAnggota().getNama();
                o[3] = Helpers.formatRupiah(pinjaman.getJumlah());
                o[4] = pinjaman.getBunga();
                o[5] = Helpers.formatRupiah(pinjaman.getTotalPinjaman());
                o[6] = pinjaman.getStatus();
                o[7] = pinjaman.getKeterangan();
                o[8] = df.format(pinjaman.getTanggalTransaksi());
                tblModel.addRow(o);
            }

            tblPinjaman.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            tblPinjaman.setModel(tblModel);
        }
    }

    private void resetForm() {
        inputIdPinjaman.setText("");
        inputJumlah.setText("");
        inputTotalPinjaman.setText("");
        inputKeterangan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupType = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputAnggota = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        inputJumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputKeterangan = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        inputIdPinjaman = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        inputBunga = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        inputTotalPinjaman = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPinjaman = new javax.swing.JTable();

        jLabel3.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Data Pinjaman");

        jLabel1.setText("Anggota:");

        inputAnggota.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setText("Jumlah:");

        inputJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputJumlahKeyTyped(evt);
            }
        });

        jLabel4.setText("Bunga:");

        jLabel5.setText("Keterangan:");

        inputKeterangan.setColumns(20);
        inputKeterangan.setRows(5);
        jScrollPane1.setViewportView(inputKeterangan);

        jLabel6.setText("ID Pinjaman:");

        inputIdPinjaman.setEnabled(false);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Fira Sans", 2, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("*Kode Transaksi akan di generate otomatis");

        inputBunga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "15%", "20%" }));

        jLabel8.setText("Total Pinjaman:");

        inputTotalPinjaman.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addComponent(inputAnggota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputJumlah)
                    .addComponent(inputIdPinjaman)
                    .addComponent(inputBunga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputTotalPinjaman))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputIdPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputTotalPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblPinjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pinjaman", "NIK", "Nama Anggota", "Jumlah", "Bunga", "Total Pinjaman", "Status", "Keterangan", "Tanggal Transaksi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPinjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPinjamanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPinjaman);
        if (tblPinjaman.getColumnModel().getColumnCount() > 0) {
            tblPinjaman.getColumnModel().getColumn(8).setResizable(false);
            tblPinjaman.getColumnModel().getColumn(8).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3)
                    .addContainerGap(599, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void inputJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputJumlahKeyTyped
        Helpers.inputNumeric(evt);
    }//GEN-LAST:event_inputJumlahKeyTyped

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (validateInput()) {
            Pinjaman pinjamanBelumLunas = pinjamanController.getPinjamanBelumLuasByAnggota((Anggota) inputAnggota.getSelectedItem());
            if (pinjamanBelumLunas != null) {
                JOptionPane.showMessageDialog(this, "Anggota ini mempunyai Pinjaman yang BELUM LUNAS."
                        + "Untuk sementara tidak bisa megajukan pinjaman.");
                return;
            }
            
            Long jumlah = Long.valueOf(inputJumlah.getText());
            Integer bunga = Integer.valueOf(((String) inputBunga.getSelectedItem()).replace("%", ""));
            Long totalPinjaman = jumlah + (jumlah * bunga / 100);
            
            Pinjaman pinjaman = new Pinjaman()
                    .setAnggota((Anggota) inputAnggota.getSelectedItem())
                    .setJumlah(Long.parseLong(inputJumlah.getText()))
                    .setBunga(bunga)
                    .setTotalPinjaman(totalPinjaman)
                    .setStatus(Pinjaman.PinjamanStatus.BELUM_LUNAS)
                    .setKeterangan(inputKeterangan.getText());

            pinjamanController.setDML(pinjaman, CRUD.CREATE);
            JOptionPane.showMessageDialog(this, "Berhasil menambah transaksi pinjaman.");
            resetForm();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblPinjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamanMouseClicked
        inputIdPinjaman.setText(tblModel.getValueAt(tblPinjaman.getSelectedRow(), 0) + "");
        inputKeterangan.setText(tblModel.getValueAt(tblPinjaman.getSelectedRow(), 7) + "");
        inputJumlah.setText(tblModel.getValueAt(tblPinjaman.getSelectedRow(), 3) + "");
        inputAnggota.getModel().setSelectedItem(tblModel.getValueAt(tblPinjaman.getSelectedRow(), 1) + " - " + tblModel.getValueAt(tblPinjaman.getSelectedRow(), 2));
        btnSimpan.setEnabled(false);
    }//GEN-LAST:event_tblPinjamanMouseClicked

    private boolean validateInput() {
        if (inputJumlah.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Jumlah Tidak Boleh Kosong");
            return false;
        } else {
            System.out.println(inputBunga.getSelectedItem());
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupType;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> inputAnggota;
    private javax.swing.JComboBox<String> inputBunga;
    private javax.swing.JTextField inputIdPinjaman;
    private javax.swing.JTextField inputJumlah;
    private javax.swing.JTextArea inputKeterangan;
    private javax.swing.JTextField inputTotalPinjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPinjaman;
    // End of variables declaration//GEN-END:variables
}
